
-- 사용자
CREATE TABLE USER (
	USER_ID VARCHAR(20)  PRIMARY KEY, -- 사용자ID
	USER_NM VARCHAR(50)  NOT NULL, -- 이름
	EMAIL   VARCHAR(100) NULL      -- 이메일
);

-- 블로그
CREATE TABLE BLOG (
	BLOG_ID INTEGER     PRIMARY KEY AUTO_INCREMENT, -- 블로그ID
	BLOG_NM VARCHAR(50) NOT NULL, -- 블로그명
	USER_ID VARCHAR(20) NOT NULL -- 관리자ID
);

-- 포스트
CREATE TABLE POST (
	POST_ID  INTEGER       PRIMARY KEY AUTO_INCREMENT, -- 포스트ID
	SUBJECT  VARCHAR(100)  NOT NULL, -- 제목
	CONTENTS VARCHAR(1000) NOT NULL, -- 내용
	REG_DT   DATETIME      NOT NULL, -- 등록일시
	BLOG_ID  INTEGER       NOT NULL  -- 블로그ID
);

-- 블로그
ALTER TABLE BLOG
	ADD CONSTRAINT FK_USER_TO_BLOG -- 사용자 -> 블로그
		FOREIGN KEY (
			USER_ID -- 관리자ID
		)
		REFERENCES USER ( -- 사용자
			USER_ID -- 사용자ID
		);

-- 포스트
ALTER TABLE POST
	ADD CONSTRAINT FK_BLOG_TO_POST -- 블로그 -> 포스트
		FOREIGN KEY (
			BLOG_ID -- 블로그ID
		)
		REFERENCES BLOG ( -- 블로그
			BLOG_ID -- 블로그ID
		);